import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { format } from 'date-fns'
import type { CalculationResult, BankLoanResult } from '@/types/admin/calculator'

type Language = 'ka' | 'en' | 'ru'

const translations = {
  ka: {
    paymentReport: 'გადახდის გრაფიკის ანგარიში',
    bankLoanReport: 'საბანკო სესხის გაანგარიშების ანგარიში',
    project: 'პროექტი:',
    date: 'თარიღი:',
    paymentMethod: 'გადახდის მეთოდი:',
    area: 'ფართობი:',
    basePrice: 'საბაზრო ფასი:',
    bank: 'ბანკი:',
    loanTerm: 'სესხის ვადა:',
    years: 'წელი',
    months: 'თვე',
    description: 'აღწერა',
    amount: 'თანხა',
    baseTotal: 'საბაზრო ჯამი',
    priceModifier: 'ფასის მოდიფიკატორი',
    totalPrice: 'სულ ფასი',
    downPayment: 'შენატანი',
    monthlyPayment: 'ყოველთვიური გადახდა',
    numberOfMonths: 'თვეების რაოდენობა',
    finalPayment: 'საბოლოო გადახდა',
    paymentSchedule: 'გადახდის გრაფიკი',
    month: 'თვე',
    payment: 'გადახდა',
    remainingBalance: 'დარჩენილი ბალანსი',
    loanAmount: 'სესხის ოდენობა',
    interestRate: 'პროცენტული განაკვეთი',
    totalInterest: 'სულ პროცენტი',
    totalPayment: 'სულ გადახდა',
    amortizationSchedule: 'ამორტიზაციის გრაფიკი',
    principal: 'ძირი',
    interest: 'პროცენტი',
    balance: 'ბალანსი',
    page: 'გვერდი',
    of: '-დან',
    generatedBy: 'შექმნილია Unity Development გადახდის კალკულატორით',
  },
  en: {
    paymentReport: 'Payment Calculation Report',
    bankLoanReport: 'Bank Loan Calculation Report',
    project: 'Project:',
    date: 'Date:',
    paymentMethod: 'Payment Method:',
    area: 'Area:',
    basePrice: 'Base Price:',
    bank: 'Bank:',
    loanTerm: 'Loan Term:',
    years: 'years',
    months: 'months',
    description: 'Description',
    amount: 'Amount',
    baseTotal: 'Base Total',
    priceModifier: 'Price Modifier',
    totalPrice: 'Total Price',
    downPayment: 'Down Payment',
    monthlyPayment: 'Monthly Payment',
    numberOfMonths: 'Number of Months',
    finalPayment: 'Final Payment',
    paymentSchedule: 'Payment Schedule',
    month: 'Month',
    payment: 'Payment',
    remainingBalance: 'Remaining Balance',
    loanAmount: 'Loan Amount',
    interestRate: 'Interest Rate',
    totalInterest: 'Total Interest',
    totalPayment: 'Total Payment',
    amortizationSchedule: 'Amortization Schedule',
    principal: 'Principal',
    interest: 'Interest',
    balance: 'Balance',
    page: 'Page',
    of: 'of',
    generatedBy: 'Generated by Unity Development Payment Calculator',
  },
  ru: {
    paymentReport: 'Отчет о расчете оплаты',
    bankLoanReport: 'Отчет о расчете банковского кредита',
    project: 'Проект:',
    date: 'Дата:',
    paymentMethod: 'Способ оплаты:',
    area: 'Площадь:',
    basePrice: 'Базовая цена:',
    bank: 'Банк:',
    loanTerm: 'Срок кредита:',
    years: 'лет',
    months: 'месяцев',
    description: 'Описание',
    amount: 'Сумма',
    baseTotal: 'Базовая сумма',
    priceModifier: 'Модификатор цены',
    totalPrice: 'Общая цена',
    downPayment: 'Первоначальный взнос',
    monthlyPayment: 'Ежемесячный платеж',
    numberOfMonths: 'Количество месяцев',
    finalPayment: 'Финальный платеж',
    paymentSchedule: 'График платежей',
    month: 'Месяц',
    payment: 'Платеж',
    remainingBalance: 'Остаток',
    loanAmount: 'Сумма кредита',
    interestRate: 'Процентная ставка',
    totalInterest: 'Общий процент',
    totalPayment: 'Общий платеж',
    amortizationSchedule: 'График амортизации',
    principal: 'Основной долг',
    interest: 'Процент',
    balance: 'Баланс',
    page: 'Страница',
    of: 'из',
    generatedBy: 'Создано калькулятором Unity Development',
  },
}

const getDescriptionByLanguage = (description: string, lang: Language): string => {
  const parts = description.split(' / ')
  if (lang === 'ka') return parts[1] || parts[0]
  if (lang === 'en') return parts[0] || parts[1]
  // For Russian, try to use Georgian translation or fallback to English
  return parts[1] || parts[0]
}

export const useCalculatorExport = () => {
  /**
   * Format currency for display
   */
  const formatCurrency = (amount: number): string => {
    return `$${amount.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`
  }

  /**
   * Format date for display
   */
  const formatDate = (date: Date): string => {
    return format(date, 'MMM dd, yyyy')
  }

  /**
   * Export regular payment calculation to PDF
   */
  const exportCalculationToPDF = (
    result: CalculationResult,
    projectName: string,
    alternativeName: string,
    area: number,
    basePrice: number,
    lang: Language = 'en',
  ) => {
    const t = translations[lang]
    const doc = new jsPDF()

    // Header with amber gradient (simulated with rectangle)
    doc.setFillColor(245, 158, 11) // Amber-500
    doc.rect(0, 0, 210, 45, 'F')

    // Logo/Title
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(28)
    doc.text('Unity Development', 105, 20, { align: 'center' })
    doc.setFontSize(16)
    doc.text(t.paymentReport, 105, 32, { align: 'center' })

    // Reset text color
    doc.setTextColor(0, 0, 0)
    doc.setFontSize(11)

    // Project Info
    const infoY = 55
    doc.setFont('helvetica', 'bold')
    doc.text(t.project, 20, infoY)
    doc.setFont('helvetica', 'normal')
    doc.text(projectName, 60, infoY)

    doc.setFont('helvetica', 'bold')
    doc.text(t.date, 20, infoY + 7)
    doc.setFont('helvetica', 'normal')
    doc.text(new Date().toLocaleDateString('en-US'), 60, infoY + 7)

    doc.setFont('helvetica', 'bold')
    doc.text(t.paymentMethod, 20, infoY + 14)
    doc.setFont('helvetica', 'normal')
    doc.text(alternativeName, 60, infoY + 14)

    doc.setFont('helvetica', 'bold')
    doc.text(t.area, 20, infoY + 21)
    doc.setFont('helvetica', 'normal')
    doc.text(`${area} m²`, 60, infoY + 21)

    doc.setFont('helvetica', 'bold')
    doc.text(t.basePrice, 20, infoY + 28)
    doc.setFont('helvetica', 'normal')
    doc.text(formatCurrency(basePrice) + '/m²', 60, infoY + 28)

    // Summary Table
    autoTable(doc, {
      startY: infoY + 40,
      head: [[t.description, t.amount]],
      body: [
        [t.baseTotal, formatCurrency(basePrice * area)],
        [t.priceModifier, result.priceModifier],
        [t.totalPrice, formatCurrency(result.totalPrice)],
        [t.downPayment, formatCurrency(result.downPayment)],
        [
          t.monthlyPayment,
          result.monthlyPayment > 0 ? formatCurrency(result.monthlyPayment) : 'N/A',
        ],
        [t.numberOfMonths, result.numberOfMonths > 0 ? result.numberOfMonths.toString() : 'N/A'],
        [
          t.finalPayment,
          result.finalBalloonPayment > 0 ? formatCurrency(result.finalBalloonPayment) : 'N/A',
        ],
      ],
      theme: 'striped',
      headStyles: {
        fillColor: [245, 158, 11], // Amber
        fontSize: 12,
        fontStyle: 'bold',
      },
      bodyStyles: {
        fontSize: 11,
      },
      alternateRowStyles: {
        fillColor: [254, 243, 199], // Amber-100
      },
      margin: { left: 20, right: 20 },
    })

    // Payment Schedule
    if (result.paymentSchedule && result.paymentSchedule.length > 0) {
      doc.addPage()
      doc.setFontSize(18)
      doc.setTextColor(245, 158, 11)
      doc.text(t.paymentSchedule, 20, 20)

      autoTable(doc, {
        startY: 30,
        head: [[t.month, t.date, t.payment, t.remainingBalance, t.description]],
        body: result.paymentSchedule.map((item) => [
          item.month.toString(),
          formatDate(item.date),
          formatCurrency(item.amount),
          formatCurrency(item.remainingBalance),
          getDescriptionByLanguage(item.description, lang),
        ]),
        theme: 'striped',
        headStyles: {
          fillColor: [245, 158, 11],
          fontSize: 10,
        },
        bodyStyles: {
          fontSize: 9,
        },
        alternateRowStyles: {
          fillColor: [254, 243, 199],
        },
      })
    }

    // Footer on all pages
    const pageCount = doc.internal.pages.length - 1
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(9)
      doc.setTextColor(128, 128, 128)
      doc.text(`${t.page} ${i} ${t.of} ${pageCount}`, 105, doc.internal.pageSize.height - 10, {
        align: 'center',
      })
      doc.text(
        t.generatedBy,
        105,
        doc.internal.pageSize.height - 5,
        { align: 'center' },
      )
    }

    // Save with timestamp and project name
    const timestamp = format(new Date(), 'yyyy-MM-dd')
    const filename = `Unity_Development_Payment_${projectName.replace(/\s+/g, '_')}_${timestamp}.pdf`

    doc.save(filename)
  }

  /**
   * Export bank loan calculation to PDF
   */
  const exportBankLoanToPDF = (
    result: BankLoanResult,
    projectName: string,
    bankName: string,
    area: number,
    basePrice: number,
    loanTermYears: number,
    lang: Language = 'en',
  ) => {
    const t = translations[lang]
    const doc = new jsPDF()

    // Header with amber gradient
    doc.setFillColor(245, 158, 11)
    doc.rect(0, 0, 210, 45, 'F')

    // Logo/Title
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(28)
    doc.text('Unity Development', 105, 20, { align: 'center' })
    doc.setFontSize(16)
    doc.text(t.bankLoanReport, 105, 32, { align: 'center' })

    // Reset text color
    doc.setTextColor(0, 0, 0)
    doc.setFontSize(11)

    // Project Info
    const infoY = 55
    doc.setFont('helvetica', 'bold')
    doc.text(t.project, 20, infoY)
    doc.setFont('helvetica', 'normal')
    doc.text(projectName, 60, infoY)

    doc.setFont('helvetica', 'bold')
    doc.text(t.date, 20, infoY + 7)
    doc.setFont('helvetica', 'normal')
    doc.text(new Date().toLocaleDateString('en-US'), 60, infoY + 7)

    doc.setFont('helvetica', 'bold')
    doc.text(t.bank, 20, infoY + 14)
    doc.setFont('helvetica', 'normal')
    doc.text(bankName, 60, infoY + 14)

    doc.setFont('helvetica', 'bold')
    doc.text(t.area, 20, infoY + 21)
    doc.setFont('helvetica', 'normal')
    doc.text(`${area} m²`, 60, infoY + 21)

    doc.setFont('helvetica', 'bold')
    doc.text(t.basePrice, 20, infoY + 28)
    doc.setFont('helvetica', 'normal')
    doc.text(formatCurrency(basePrice) + '/m²', 60, infoY + 28)

    doc.setFont('helvetica', 'bold')
    doc.text(t.loanTerm, 20, infoY + 35)
    doc.setFont('helvetica', 'normal')
    doc.text(`${loanTermYears} ${t.years}`, 60, infoY + 35)

    // Summary Table
    autoTable(doc, {
      startY: infoY + 45,
      head: [[t.description, t.amount]],
      body: [
        [t.loanTerm, `${loanTermYears * 12} ${t.months}`],
        [t.monthlyPayment, formatCurrency(result.monthlyPayment)],
      ],
      theme: 'striped',
      headStyles: {
        fillColor: [245, 158, 11],
        fontSize: 12,
        fontStyle: 'bold',
      },
      bodyStyles: {
        fontSize: 11,
      },
      alternateRowStyles: {
        fillColor: [254, 243, 199],
      },
      margin: { left: 20, right: 20 },
    })

    // Amortization Schedule
    if (result.paymentSchedule && result.paymentSchedule.length > 0) {
      doc.addPage()
      doc.setFontSize(18)
      doc.setTextColor(245, 158, 11)
      doc.text(t.amortizationSchedule, 20, 20)

      autoTable(doc, {
        startY: 30,
        head: [[t.month, t.date, t.payment, t.balance]],
        body: result.paymentSchedule.map((item) => [
          item.month.toString(),
          formatDate(item.date),
          formatCurrency(item.payment),
          formatCurrency(item.remainingBalance),
        ]),
        theme: 'striped',
        headStyles: {
          fillColor: [245, 158, 11],
          fontSize: 9,
        },
        bodyStyles: {
          fontSize: 8,
        },
        alternateRowStyles: {
          fillColor: [254, 243, 199],
        },
      })
    }

    // Footer on all pages
    const pageCount = doc.internal.pages.length - 1
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(9)
      doc.setTextColor(128, 128, 128)
      doc.text(`${t.page} ${i} ${t.of} ${pageCount}`, 105, doc.internal.pageSize.height - 10, {
        align: 'center',
      })
      doc.text(
        t.generatedBy,
        105,
        doc.internal.pageSize.height - 5,
        { align: 'center' },
      )
    }

    // Save
    const timestamp = format(new Date(), 'yyyy-MM-dd')
    const filename = `Unity_Development_Bank_Loan_${bankName.replace(/\s+/g, '_')}_${timestamp}.pdf`

    doc.save(filename)
  }

  return {
    exportCalculationToPDF,
    exportBankLoanToPDF,
    formatCurrency,
    formatDate,
  }
}
