/**
 * Calculator PDF Translation Constants
 * Translations for payment and bank loan PDF reports
 */

export type PDFLanguage = 'ka' | 'en' | 'ru'

export interface PDFTranslations {
  paymentReport: string
  bankLoanReport: string
  project: string
  date: string
  paymentMethod: string
  area: string
  basePrice: string
  bank: string
  loanTerm: string
  years: string
  months: string
  description: string
  amount: string
  baseTotal: string
  priceModifier: string
  totalPrice: string
  downPayment: string
  monthlyPayment: string
  numberOfMonths: string
  finalPayment: string
  paymentSchedule: string
  month: string
  payment: string
  remainingBalance: string
  loanAmount: string
  interestRate: string
  totalInterest: string
  totalPayment: string
  amortizationSchedule: string
  principal: string
  interest: string
  balance: string
  page: string
  of: string
  generatedBy: string
}

export const pdfTranslations: Record<PDFLanguage, PDFTranslations> = {
  ka: {
    paymentReport: 'გადახდის გრაფიკის ანგარიში',
    bankLoanReport: 'საბანკო სესხის გაანგარიშების ანგარიში',
    project: 'პროექტი:',
    date: 'თარიღი:',
    paymentMethod: 'გადახდის მეთოდი:',
    area: 'ფართობი:',
    basePrice: 'საბაზრო ფასი:',
    bank: 'ბანკი:',
    loanTerm: 'სესხის ვადა:',
    years: 'წელი',
    months: 'თვე',
    description: 'აღწერა',
    amount: 'თანხა',
    baseTotal: 'საბაზრო ჯამი',
    priceModifier: 'ფასის მოდიფიკატორი',
    totalPrice: 'სულ ფასი',
    downPayment: 'შენატანი',
    monthlyPayment: 'ყოველთვიური გადახდა',
    numberOfMonths: 'თვეების რაოდენობა',
    finalPayment: 'საბოლოო გადახდა',
    paymentSchedule: 'გადახდის გრაფიკი',
    month: 'თვე',
    payment: 'გადახდა',
    remainingBalance: 'დარჩენილი ბალანსი',
    loanAmount: 'სესხის ოდენობა',
    interestRate: 'პროცენტული განაკვეთი',
    totalInterest: 'სულ პროცენტი',
    totalPayment: 'სულ გადახდა',
    amortizationSchedule: 'ამორტიზაციის გრაფიკი',
    principal: 'ძირი',
    interest: 'პროცენტი',
    balance: 'ბალანსი',
    page: 'გვერდი',
    of: '-დან',
    generatedBy: 'შექმნილია Unity Development გადახდის კალკულატორით',
  },
  en: {
    paymentReport: 'Payment Calculation Report',
    bankLoanReport: 'Bank Loan Calculation Report',
    project: 'Project:',
    date: 'Date:',
    paymentMethod: 'Payment Method:',
    area: 'Area:',
    basePrice: 'Base Price:',
    bank: 'Bank:',
    loanTerm: 'Loan Term:',
    years: 'years',
    months: 'months',
    description: 'Description',
    amount: 'Amount',
    baseTotal: 'Base Total',
    priceModifier: 'Price Modifier',
    totalPrice: 'Total Price',
    downPayment: 'Down Payment',
    monthlyPayment: 'Monthly Payment',
    numberOfMonths: 'Number of Months',
    finalPayment: 'Final Payment',
    paymentSchedule: 'Payment Schedule',
    month: 'Month',
    payment: 'Payment',
    remainingBalance: 'Remaining Balance',
    loanAmount: 'Loan Amount',
    interestRate: 'Interest Rate',
    totalInterest: 'Total Interest',
    totalPayment: 'Total Payment',
    amortizationSchedule: 'Amortization Schedule',
    principal: 'Principal',
    interest: 'Interest',
    balance: 'Balance',
    page: 'Page',
    of: 'of',
    generatedBy: 'Generated by Unity Development Payment Calculator',
  },
  ru: {
    paymentReport: 'Отчет о расчете оплаты',
    bankLoanReport: 'Отчет о расчете банковского кредита',
    project: 'Проект:',
    date: 'Дата:',
    paymentMethod: 'Способ оплаты:',
    area: 'Площадь:',
    basePrice: 'Базовая цена:',
    bank: 'Банк:',
    loanTerm: 'Срок кредита:',
    years: 'лет',
    months: 'месяцев',
    description: 'Описание',
    amount: 'Сумма',
    baseTotal: 'Базовая сумма',
    priceModifier: 'Модификатор цены',
    totalPrice: 'Общая цена',
    downPayment: 'Первоначальный взнос',
    monthlyPayment: 'Ежемесячный платеж',
    numberOfMonths: 'Количество месяцев',
    finalPayment: 'Финальный платеж',
    paymentSchedule: 'График платежей',
    month: 'Месяц',
    payment: 'Платеж',
    remainingBalance: 'Остаток',
    loanAmount: 'Сумма кредита',
    interestRate: 'Процентная ставка',
    totalInterest: 'Общий процент',
    totalPayment: 'Общий платеж',
    amortizationSchedule: 'График амортизации',
    principal: 'Основной долг',
    interest: 'Процент',
    balance: 'Баланс',
    page: 'Страница',
    of: 'из',
    generatedBy: 'Создано калькулятором Unity Development',
  },
}

/**
 * Get description by language from bilingual string
 */
export function getDescriptionByLanguage(description: string, lang: PDFLanguage): string {
  const parts = description.split(' / ')
  if (lang === 'ka') return parts[1] || parts[0]
  if (lang === 'en') return parts[0] || parts[1]
  return parts[1] || parts[0]
}
