export { default as IconCommunity } from './IconCommunity.vue'
export { default as IconDocumentation } from './IconDocumentation.vue'
export { default as IconEcosystem } from './IconEcosystem.vue'
export { default as IconEmail } from './IconEmail.vue'
export { default as IconLocation } from './IconLocation.vue'
export { default as IconPhone } from './IconPhone.vue'
export { default as IconSupport } from './IconSupport.vue'
export { default as IconTooling } from './IconTooling.vue'
